export default function Page() {
  const qaList = [
    { q: "What is manual testing?", a: "Manual testing is the process of testing software manually without using automation tools. Testers execute test cases step by step to find defects." },
    { q: "What are the advantages of manual testing?", a: "Manual testing allows for exploratory testing, can catch usability issues, is flexible for ad-hoc testing, and doesn't require programming skills." },
    { q: "What are the disadvantages of manual testing?", a: "Manual testing is time-consuming, prone to human error, not repeatable for regression testing, and can't handle large data sets." },
    { q: "What is exploratory testing?", a: "Exploratory testing is an unscripted approach where testers learn about the software while testing it, using their experience to find defects." },
    { q: "What is ad-hoc testing?", a: "Ad-hoc testing is informal testing without documentation or test cases, performed randomly to find defects that formal testing might miss." },
    { q: "What is the difference between functional and non-functional testing?", a: "Functional testing verifies what the system does, while non-functional testing verifies how well the system performs (performance, usability, security)." },
    { q: "What is usability testing?", a: "Usability testing evaluates how easy and user-friendly the software is for end users." },
    { q: "What is compatibility testing?", a: "Compatibility testing ensures the software works across different browsers, devices, and operating systems." },
    { q: "What is smoke testing?", a: "Smoke testing is a preliminary test to check if the basic functionality of the application works before detailed testing." },
    { q: "What is sanity testing?", a: "Sanity testing verifies that a specific bug fix or small change doesn't break the existing functionality." },
    { q: "What is regression testing?", a: "Regression testing ensures that recent changes don't break existing functionality." },
    { q: "What is the difference between smoke and sanity testing?", a: "Smoke testing checks basic functionality after a build, while sanity testing checks specific areas after bug fixes." },
    { q: "What is black box testing?", a: "Black box testing tests the functionality of the software without knowledge of internal code structure." },
    { q: "What is white box testing?", a: "White box testing requires knowledge of internal code structure and tests the code logic." },
    { q: "What is grey box testing?", a: "Grey box testing combines black box and white box approaches, with partial knowledge of internal structure." },
    { q: "What is equivalence partitioning?", a: "Equivalence partitioning divides input data into valid and invalid partitions to reduce test cases." },
    { q: "What is boundary value analysis?", a: "Boundary value analysis tests the boundaries between equivalence partitions." },
    { q: "What is decision table testing?", a: "Decision table testing uses tables to represent combinations of conditions and actions." },
    { q: "What is state transition testing?", a: "State transition testing tests how the system behaves when transitioning between different states." },
    { q: "What is use case testing?", a: "Use case testing tests scenarios based on how users interact with the system." },
    { q: "What is user acceptance testing (UAT)?", a: "UAT is performed by end users to ensure the software meets their requirements and is ready for production." },
    { q: "What is alpha testing?", a: "Alpha testing is internal testing performed by developers or QA team in a controlled environment." },
    { q: "What is beta testing?", a: "Beta testing is external testing performed by end users in a real environment." },
    { q: "What is gamma testing?", a: "Gamma testing is the final testing phase before release, focusing on documentation and final bug fixes." },
    { q: "What is a test case?", a: "A test case is a set of conditions and steps to verify a specific feature or functionality." },
    { q: "What is a test scenario?", a: "A test scenario is a high-level description of what to test, containing multiple test cases." },
    { q: "What is a test script?", a: "A test script is a document containing detailed steps for executing a test case." },
    { q: "What is a defect?", a: "A defect is any flaw in the software that causes it to behave incorrectly or not as expected." },
    { q: "What is a bug?", a: "A bug is a defect found during testing that needs to be fixed." },
    { q: "What is severity?", a: "Severity measures the impact of a defect on the software functionality." },
    { q: "What is priority?", a: "Priority indicates the urgency of fixing a defect based on business impact." },
    { q: "What is the difference between severity and priority?", a: "Severity is technical impact, priority is business urgency." },
    { q: "What is the bug life cycle?", a: "Bug life cycle: New → Assigned → Open → Fixed → Retest → Verified → Closed/Reopened." },
    { q: "What is a test plan?", a: "A test plan is a document describing scope, approach, resources, and schedule for testing." },
    { q: "What is a test summary report?", a: "A test summary report provides an overview of testing activities, results, and metrics." },
    { q: "What is test coverage?", a: "Test coverage measures how much of the application has been tested." },
    { q: "What is traceability matrix?", a: "A traceability matrix links requirements to test cases to ensure all requirements are tested." },
    { q: "What is a test environment?", a: "A test environment is the setup where testing is performed, including hardware, software, and data." },
    { q: "What is a staging environment?", a: "A staging environment mimics production for final testing before release." },
    { q: "What is a defect density?", a: "Defect density is the number of defects per size unit of software (e.g., per 1000 lines of code)." },
    { q: "What is defect leakage?", a: "Defect leakage is when defects are found by customers that were missed during testing." },
    { q: "What is the pesticide paradox?", a: "The pesticide paradox states that repeatedly running the same tests becomes less effective at finding defects." },
    { q: "What is monkey testing?", a: "Monkey testing is random testing without any test cases or scenarios." },
    { q: "What is gorilla testing?", a: "Gorilla testing focuses intensively on one module or feature." },
    { q: "What is the difference between error, defect, and failure?", a: "Error is a mistake by developer, defect is the flaw in software, failure is the incorrect behavior observed." },
    { q: "What is positive testing?", a: "Positive testing verifies that the system works with valid inputs." },
    { q: "What is negative testing?", a: "Negative testing verifies that the system handles invalid inputs gracefully." },
    { q: "What is mutation testing?", a: "Mutation testing involves making small changes to code to verify test cases can detect them." },
    { q: "What is static testing?", a: "Static testing reviews documents and code without executing the software." },
    { q: "What is dynamic testing?", a: "Dynamic testing executes the software to find defects." },
    { q: "What is the difference between verification and validation?", a: "Verification checks if we are building the product right, validation checks if we are building the right product." },
    { q: "What is the exit criteria for testing?", a: "Exit criteria define when testing can stop, such as test coverage percentage, defect density, etc." },
    { q: "What is the entry criteria for testing?", a: "Entry criteria define when testing can start, such as stable build, test environment ready, etc." },
    { q: "What is risk-based testing?", a: "Risk-based testing prioritizes testing based on the likelihood and impact of risks." },
    { q: "What is requirements-based testing?", a: "Requirements-based testing ensures all specified requirements are tested." },
    { q: "What is experience-based testing?", a: "Experience-based testing uses tester knowledge and experience to find defects." },
    { q: "What is the difference between retesting and regression testing?", a: "Retesting verifies a specific fix, regression testing ensures no new defects were introduced." },
    { q: "What is a test harness?", a: "A test harness is a collection of software and test data used to test a program unit." },
    { q: "What is a test stub?", a: "A test stub is a minimal implementation of a component used for testing." },
    { q: "What is a test driver?", a: "A test driver is a program that calls the component being tested." },
    { q: "What is internationalization testing?", a: "Internationalization testing ensures software can be adapted for different locales." },
    { q: "What is localization testing?", a: "Localization testing verifies software works in a specific locale." },
    { q: "What is accessibility testing?", a: "Accessibility testing ensures software is usable by people with disabilities." },
    { q: "What is the difference between load and stress testing?", a: "Load testing checks performance under expected load, stress testing checks behavior under extreme conditions." },
    { q: "What is volume testing?", a: "Volume testing checks system behavior with large amounts of data." },
    { q: "What is spike testing?", a: "Spike testing checks system behavior when load suddenly increases." },
    { q: "What is soak testing?", a: "Soak testing checks system stability over an extended period." },
    { q: "What is concurrency testing?", a: "Concurrency testing checks how the system handles multiple users simultaneously." },
    { q: "What is thread safety?", a: "Thread safety ensures that shared data is accessed correctly by multiple threads." },
    { q: "What is race condition?", a: "A race condition occurs when the behavior depends on the timing of uncontrollable events." },
    { q: "What is deadlock?", a: "Deadlock occurs when two or more processes wait for each other to release resources." },
    { q: "What is a memory leak?", a: "A memory leak occurs when a program fails to release memory it no longer needs." },
    { q: "What is buffer overflow?", a: "Buffer overflow occurs when data exceeds the buffer capacity." },
    { q: "What is SQL injection?", a: "SQL injection is a security vulnerability where malicious SQL is inserted into queries." },
    { q: "What is cross-site scripting (XSS)?", a: "XSS is a security vulnerability where malicious scripts are injected into web pages." },
    { q: "What is cross-site request forgery (CSRF)?", a: "CSRF is an attack that tricks users into performing unwanted actions." },
    { q: "What is session hijacking?", a: "Session hijacking involves stealing a user's session to gain unauthorized access." },
    { q: "What is a man-in-the-middle attack?", a: "A man-in-the-middle attack intercepts communication between two parties." },
    { q: "What is encryption?", a: "Encryption converts data into a coded format to prevent unauthorized access." },
    { q: "What is hashing?", a: "Hashing converts data into a fixed-size string for verification." },
    { q: "What is a digital certificate?", a: "A digital certificate verifies the identity of a website or user." },
    { q: "What is two-factor authentication?", a: "Two-factor authentication requires two forms of verification." },
    { q: "What is biometric authentication?", a: "Biometric authentication uses physical characteristics for verification." },
    { q: "What is a firewall?", a: "A firewall controls network traffic based on security rules." },
    { q: "What is an intrusion detection system (IDS)?", a: "An IDS monitors network traffic for suspicious activity." },
    { q: "What is an intrusion prevention system (IPS)?", a: "An IPS actively blocks detected threats." },
    { q: "What is a vulnerability assessment?", a: "A vulnerability assessment identifies security weaknesses." },
    { q: "What is penetration testing?", a: "Penetration testing simulates attacks to find vulnerabilities." },
    { q: "What is ethical hacking?", a: "Ethical hacking involves authorized attempts to find security vulnerabilities." },
    { q: "What is compliance testing?", a: "Compliance testing ensures adherence to standards and regulations." },
    { q: "What is GDPR?", a: "GDPR is the General Data Protection Regulation for data privacy." },
    { q: "What is HIPAA?", a: "HIPAA protects health information privacy in the US." },
    { q: "What is PCI DSS?", a: "PCI DSS ensures secure handling of payment card data." },
    { q: "What is SOX?", a: "SOX ensures accurate financial reporting." },
    { q: "What is ISO 27001?", a: "ISO 27001 is an information security management standard." },
    { q: "What is ITIL?", a: "ITIL is a framework for IT service management." },
    { q: "What is COBIT?", a: "COBIT is a framework for IT governance and management." },
    { q: "What is CMMI?", a: "CMMI is a model for process improvement." },
    { q: "What is Six Sigma?", a: "Six Sigma is a methodology for quality improvement." },
    { q: "What is Lean?", a: "Lean focuses on eliminating waste in processes." },
    { q: "What is Agile?", a: "Agile is an iterative approach to software development." },
    { q: "What is Scrum?", a: "Scrum is an agile framework with sprints and roles." },
    { q: "What is Kanban?", a: "Kanban is a visual method for managing work." },
    { q: "What is XP (Extreme Programming)?", a: "XP is an agile methodology emphasizing technical practices." },
    { q: "What is TDD?", a: "Test Driven Development writes tests before code." },
    { q: "What is BDD?", a: "Behavior Driven Development uses natural language for tests." },
    { q: "What is ATDD?", a: "Acceptance Test Driven Development involves stakeholders in defining acceptance criteria." },
    { q: "What is CI/CD?", a: "Continuous Integration/Continuous Deployment automates building, testing, and deployment." },
    { q: "What is DevOps?", a: "DevOps combines development and operations for faster delivery." },
    { q: "What is infrastructure as code?", a: "Infrastructure as code manages infrastructure with code." },
    { q: "What is containerization?", a: "Containerization packages applications with dependencies." },
    { q: "What is Docker?", a: "Docker is a platform for developing, shipping, and running applications in containers." },
    { q: "What is Kubernetes?", a: "Kubernetes is a system for automating deployment and scaling of containerized applications." },
    { q: "What is microservices?", a: "Microservices is an architectural style where applications are composed of small, independent services." },
    { q: "What is monolithic architecture?", a: "Monolithic architecture has all components tightly coupled in a single application." },
    { q: "What is serverless computing?", a: "Serverless computing runs code without managing servers." },
    { q: "What is cloud computing?", a: "Cloud computing delivers computing services over the internet." },
    { q: "What is IaaS?", a: "Infrastructure as a Service provides virtualized computing resources." },
    { q: "What is PaaS?", a: "Platform as a Service provides a platform for developing and deploying applications." },
    { q: "What is SaaS?", a: "Software as a Service delivers software applications over the internet." },
    { q: "What is API?", a: "Application Programming Interface defines how software components interact." },
    { q: "What is REST?", a: "Representational State Transfer is an architectural style for web services." },
    { q: "What is SOAP?", a: "Simple Object Access Protocol is a protocol for exchanging structured information." },
    { q: "What is GraphQL?", a: "GraphQL is a query language for APIs that allows clients to request exactly the data they need." },
    { q: "What is JSON?", a: "JavaScript Object Notation is a lightweight data interchange format." },
    { q: "What is XML?", a: "Extensible Markup Language is a markup language for encoding documents." },
    { q: "What is HTTP?", a: "HyperText Transfer Protocol is the foundation of data communication on the web." },
    { q: "What is HTTPS?", a: "HTTPS is the secure version of HTTP using SSL/TLS encryption." },
    { q: "What is a status code?", a: "A status code indicates the result of an HTTP request." },
    { q: "What is authentication?", a: "Authentication verifies the identity of a user or system." },
    { q: "What is authorization?", a: "Authorization determines what actions an authenticated user can perform." },
    { q: "What is OAuth?", a: "OAuth is an open standard for access delegation." },
    { q: "What is JWT?", a: "JSON Web Token is a compact way to represent claims between parties." },
    { q: "What is SAML?", a: "Security Assertion Markup Language is an XML-based standard for exchanging authentication data." },
    { q: "What is CORS?", a: "Cross-Origin Resource Sharing allows web pages to make requests to different domains." },
    { q: "What is a cookie?", a: "A cookie is a small piece of data stored on the user's computer by the web browser." },
    { q: "What is a session?", a: "A session maintains state information between HTTP requests." },
    { q: "What is caching?", a: "Caching stores frequently accessed data for faster retrieval." },
    { q: "What is CDN?", a: "Content Delivery Network distributes content geographically for faster delivery." },
    { q: "What is load balancing?", a: "Load balancing distributes traffic across multiple servers." },
    { q: "What is failover?", a: "Failover automatically switches to a backup system when the primary fails." },
    { q: "What is high availability?", a: "High availability ensures systems remain operational for long periods." },
    { q: "What is disaster recovery?", a: "Disaster recovery involves restoring systems after a major incident." },
    { q: "What is business continuity?", a: "Business continuity ensures critical business functions continue during disruptions." },
    { q: "What is monitoring?", a: "Monitoring tracks system performance and health." },
    { q: "What is logging?", a: "Logging records events and activities in the system." },
    { q: "What is alerting?", a: "Alerting notifies administrators of issues." },
    { q: "What is a dashboard?", a: "A dashboard displays key metrics and system status." },
    { q: "What is APM?", a: "Application Performance Monitoring tracks application performance." },
    { q: "What is RUM?", a: "Real User Monitoring measures actual user experience." },
    { q: "What is synthetic monitoring?", a: "Synthetic monitoring simulates user interactions to test performance." },
    { q: "What is A/B testing?", a: "A/B testing compares two versions to determine which performs better." },
    { q: "What is multivariate testing?", a: "Multivariate testing compares multiple variables simultaneously." },
    { q: "What is feature flagging?", a: "Feature flagging allows enabling/disabling features without deployment." },
    { q: "What is canary deployment?", a: "Canary deployment releases new features to a small subset of users first." },
    { q: "What is blue-green deployment?", a: "Blue-green deployment maintains two identical environments for seamless switching." },
    { q: "What is rolling deployment?", a: "Rolling deployment gradually replaces old versions with new ones." },
    { q: "What is version control?", a: "Version control tracks changes to code over time." },
    { q: "What is Git?", a: "Git is a distributed version control system." },
    { q: "What is GitHub?", a: "GitHub is a platform for hosting and collaborating on Git repositories." },
    { q: "What is a commit?", a: "A commit saves changes to the repository with a message." },
    { q: "What is a branch?", a: "A branch is a separate line of development." },
    { q: "What is a merge?", a: "A merge combines changes from different branches." },
    { q: "What is a pull request?", a: "A pull request proposes changes to be merged into the main branch." },
    { q: "What is code review?", a: "Code review examines code for quality and correctness." },
    { q: "What is pair programming?", a: "Pair programming involves two developers working together on code." },
    { q: "What is mob programming?", a: "Mob programming involves the whole team working on the same code." },
    { q: "What is refactoring?", a: "Refactoring improves code structure without changing functionality." },
    { q: "What is technical debt?", a: "Technical debt is the cost of maintaining suboptimal code." },
    { q: "What is code smell?", a: "Code smell indicates potential problems in code." },
    { q: "What is clean code?", a: "Clean code is code that is easy to read, understand, and maintain." },
    { q: "What is SOLID principles?", a: "SOLID is an acronym for five design principles: Single responsibility, Open-closed, Liskov substitution, Interface segregation, Dependency inversion." },
    { q: "What is DRY?", a: "Don't Repeat Yourself - avoid code duplication." },
    { q: "What is KISS?", a: "Keep It Simple, Stupid - prefer simple solutions." },
    { q: "What is YAGNI?", a: "You Aren't Gonna Need It - don't add unnecessary features." },
    { q: "What is the difference between QA and QC?", a: "QA prevents defects, QC detects defects." },
    { q: "What is the role of a QA engineer?", a: "A QA engineer ensures software quality through planning, executing, and reporting on tests." },
    { q: "What skills does a QA engineer need?", a: "Technical skills, analytical thinking, attention to detail, communication, and domain knowledge." },
    { q: "What is the QA career path?", a: "QA Analyst → Senior QA → QA Lead → QA Manager → Test Architect." },
    { q: "What certifications are valuable for QA?", a: "ISTQB, CSTE, CSQA, CTFL, CTAL." },
    { q: "What tools do QA engineers use?", a: "JIRA, TestRail, Selenium, Postman, JMeter, Appium, BrowserStack." },
    { q: "What is the difference between QA and testing?", a: "Testing is part of QA; QA includes processes to ensure quality throughout development." },
    { q: "What is the future of QA?", a: "Shift-left testing, AI/ML in testing, DevOps integration, and test automation growth." },
  ]

  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold mb-6">Manual Testing Q&A</h1>
      <p className="mb-4">
        Comprehensive interview questions and answers specifically for manual testing roles.
      </p>
      <div className="space-y-4">
        {qaList.map((item, index) => (
          <div key={index} className="border border-gray-300 dark:border-gray-600 rounded-lg p-4">
            <h3 className="font-semibold mb-2">Q: {item.q}</h3>
            <p className="text-gray-700 dark:text-gray-300">A: {item.a}</p>
          </div>
        ))}
      </div>
    </div>
  )
}
